export default {
    SIGNAL: "signal",
    COMMLOST: "commlost",
    COMMLOST_END: "commlost_end",
    ONBATT: "onbatt",
    ONBATT_END: "onbatt_end",
    OFFLINE: "offline",
    ONLINE: "online",
    LINE_OK: "line_ok",
    TRIM: "trim",
    BOOST: "boost",
    OVERLOAD: "overload",
    OVERLOAD_END: "overload_end",
    NOBATT: "nobatt",
    NOBATT_END: "nobatt_end",
    TURNED_ON: "turned_on",
    TURNED_OFF: "turned_off",
};