export default {
    COMMFAILURE: "commfailure",
    COMMOK: "commok",
    STARTSELFTEST: "startselftest",
    ENDSELFTEST: "endselftest",
    POWEROUT: "powerout",
    MAINSBACK: "mainsback",
    ONBATTERY: "onbattery",
    OFFBATTERY: "offbattery",
    BATTATTACH: "battattach",
    CHANGEME: "changeme",
    FAILING: "failing",
    TIMEOUT: "timeout",
    LOADLIMIT: "loadlimit",
    DOSHUTDOWN: "doshutdown",
    ANNOYME: "annoyme",
    REMOTEDOWN: "remotedown",
};